### ISSUE TITLE
protoc-gen-elmer + Buf + multiple .proto files in a package

### ISSUE THREAD

**Issue by houseofmercy-github** [feral-dot-io/protoc-gen-elmer#1] opened 2022-08-10 19:22 UTC
## Background

I would like to use **protoc-gen-elmer** in my Elm project where I'll be passing protobuf messages between my Elm logic and some javascript libraries via Elm ports.  I'm also using [Buf](https://docs.buf.build/introduction) to manage all the generation.  I've done some experiments with [**protoc-gen-elm**](https://github.com/andreasewering/protoc-gen-elm) and [**protoc-gen-ts_proto**](https://github.com/stephenh/ts-proto) which work as expected.   However I'm having problems with protoc-gen-elmer.

## Problem

Although the .proto files in my project have distinct names using protoc-gen-elmer from Buf generates only one file derived from the package name with generated code for only one of the .proto files and here is a warning from Buf indicating that the file is being overwritten.

## To Reproduce 

Please see this gist for a repro: https://gist.github.com/houseofmercy-github/97caa4ff100681ccbae42e699a8c28a1

The remainder of this comment duplicates the information in the README.md from that gist.

________

## To reproduce

Included are the Makefile and some scripts to demonstrate the problem.

    .
    ├── Makefile
    ├── README.md
    ├── _generate.sh
    ├── _setup.sh
    ├── _untar.sh
    └── buf.tgz

GitHub gists do not allow directories so buf/ subdir is added as a tar bundle.

### Assumptions

* yarn, node, etc installed
* protoc installed
* [buf.build](https://docs.buf.build/installation) CLI installed

### Steps

* cd to directory where you extracted these files
* run "make setup"

Observe output

    ...
    ├─ ts-proto-descriptors@1.7.1
    └─ ts-proto@1.121.5
    ✨  Done in 1.66s.
    ====== Please copy protoc-gen-elmer to ./bin =======

* copy your protoc-gen-elmer the bin directory 
* run "make generate"

If you failed to copy protoc-gen-elmer you'll see an error.
Otherwise you should observe

    % make generate
      ./_generate.sh
	  Warning: Duplicate generated file name "Model/V1.elm". 
	  Buf will continue without error here and drop the second occurrence 
      of this file, but please raise an issue with the maintainer of the plugin.
      ./_generate.sh done

### Compare directory trees

Here is the result I observe showing the buf/ directory after generating the gen/ directory.

    buf
    ├── Model                               \ original proto organization
    │   └── v1                              |  following Buf recommentations
    │       ├── Client.proto                | Client.proto imports Model/v1/Error.proto
    │       └── Error.proto                 /  for Model.v1.Errors structure
    │
    ├── buf.gen.yaml
    ├── buf.yaml
    │
    └── gen
        ├── elm
        │   └── Proto                       \ with Buf and protoc-gen-elm the tree
        │       └── Model                   |  preserves structure 
        │           └── V1                  |
        │               ├── Client.elm      |
        │               └── Error.elm       /
        │
        ├── elmer                           \ unfortunately with Buf protoc-gen-elmer
        │   └── Model                       | overwrites output from Client.proto with
        │       └── V1.elm                  / output from Error.proto and loses structure
        │
        └── ts_proto                        \
            └── Model                       | typescript ts-proto output for reference
                └── v1                      | (we need to read/write protobuf messages 
                    ├── Client.ts           |  on js side of an Elm port)
                    └── Error.ts            /

**Comment by feral-dot-io** [comment] 2022-08-26 20:09
Thank you for the wonderfully documented first issue!

The tool assumed that there was one file per package and generated an Elm module on that basis -- I have no idea how I managed to miss that. The fix was easy enough since files can be merged and this can be fed back into the codegen as normal. You'll then get one Elm module per package as intended.

Here's the test case with your name on it: https://github.com/feral-dot-io/protoc-gen-elmer/blob/192917236cad55d5cd6a7282157cb5bb7f1f7e69/pkg/elmgen/imports_test.go#L125

You are likely to find issues around imports (well-known types and your own packages) that `protoc-gen-elmer` handles fine. It's one of the reasons why I built this tool.

I'm also watching [Buf's Connect](https://connect.build/) with a keen eye and will probably add a client at some point. It promises full duplex streaming :)

Good luck with your experiments.

**Closed as completed** 2022-08-26 20:10 UTC
